import Foundation
import UniformTypeIdentifiers

struct IncomingRepresentation {
    let type: UTType
    let data: Data
}

struct IncomingClip {
    var representations: [IncomingRepresentation]
    var suggestedName: String?
}

enum ItemProviderLoader {
    static let sensitiveTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
    ]

    private static let ignoredPrefixes = ["dyn.", "com.apple.uikit.", "com.apple.is-remote-clipboard"]

    /// nil when the item is marked sensitive (password managers etc.)
    static func load(_ provider: NSItemProvider) async -> IncomingClip? {
        let ids = provider.registeredTypeIdentifiers
        if ids.contains(where: sensitiveTypes.contains) { return nil }
        var reps: [IncomingRepresentation] = []
        for id in ids where !ignoredPrefixes.contains(where: id.hasPrefix) {
            guard let type = UTType(id), let data = await loadData(provider, id), !data.isEmpty else { continue }
            reps.append(IncomingRepresentation(type: type, data: data))
        }
        return IncomingClip(representations: reps, suggestedName: provider.suggestedName)
    }

    private static func loadData(_ provider: NSItemProvider, _ id: String) async -> Data? {
        await withCheckedContinuation { continuation in
            _ = provider.loadDataRepresentation(forTypeIdentifier: id) { data, _ in
                continuation.resume(returning: data)
            }
        }
    }
}
